apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
   name: webingress
spec:
   ingressClassName: nginx
   rules:
   - host: "www.demo.com"
     http:
       paths:
       - path: "/wear"
         pathType: Prefix
         backend:
           service:
            name: wear-service
            port:
             number: 8080
       - path: "/watch"
         pathType: Prefix
         backend:
           service:
            name: video-service
            port:
             number: 8080
       - path: "/eat"
         pathType: Prefix
         backend:
           service:
            name: food-service
            port:
             number: 8080
        
